basic.forever(function () {
    basic.showIcon(IconNames.Heart)
    music.playMelody("G B A G C5 B A B ", 120)
    basic.showString("Helena")
    basic.showIcon(IconNames.SmallHeart)
    music.playMelody("B A G A G F A C5 ", 120)
    basic.showString("Linus")
    basic.showIcon(IconNames.Giraffe)
    music.playMelody("C5 A B G A F G E ", 120)
    basic.showString("Nicole")
    basic.showIcon(IconNames.Duck)
    music.playMelody("C5 G B A F A C5 B ", 120)
    basic.showString("Thomas")
})
